############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Why Breachsense"
url = "why-breachsense/"
weight = 2

[[main]]
weight = 3
name = "Platform"
hasChildren = true

  [[main]]
  parent = "Platform"
  name = "Dark Web Monitoring"
  url = "dark-web-monitoring/"
  weight = 1
  
  [[main]]
  parent = "Platform"
  name = "Data Breach Monitoring"
  url = "data-breach-monitoring/"
  weight = 2

[[main]]
weight = 4
name = "Solutions"
hasChildren = true

  [[main]]
  parent = "Solutions"
  name = "Enterprise Security Teams"
  url = "enterprise-security-teams/"
  weight = 1

  [[main]]
  parent = "Solutions"
  name = "Penetration Testing"
  url = "penetration-testing/"
  weight = 2

  [[main]]
  parent = "Solutions"
  name = "Prevent Ransomware"
  url = "prevent-ransomware/"
  weight = 3
  [[main]]

  parent = "Solutions"
  name = "Managed Service Providers"
  url = "managed-service-providers/"
  weight = 4

[[main]]
name = "Recent Breaches"
url = "breaches/"
weight = 5

[[main]]
  name = "Dark Web Scanner"
  url = "dark-web-scanner/"
  weight = 6

#[[main]]
#name = "About"
#url = "about/"
#weight = 7

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 8

[[main]]
weight = 9
name = "Resources"
hasChildren = true

  [[main]]
  parent = "Resources"
  name = "About"
  url = "about/"
  weight = 1

  [[main]]
  parent = "Resources"
  name = "Blog"
  url = "blog/"
  weight = 2

  [[main]]
  parent = "Resources"
  name = "Documentation"
  url = "documentation/"
  weight = 3

  [[main]]
  parent = "Resources"
  name = "Darknet Markets"
  url = "darknet-markets/"
  weight = 4
  
  [[main]]
  parent = "Resources"
  name = "Ransomware Gangs"
  url = "ransomware-gangs/"
  weight = 5

  [[main]]
  parent = "Resources"
  name = "Telegram Channels"
  url = "telegram-channels/"
  weight = 6

  [[main]]
  parent = "Resources"
  name = "Terms & Conditions"
  url = "terms-and-conditions/"
  weight = 10

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3

