############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
weight = 6
name = "Resources"
hasChildren = true
  
  [[main]]
  parent = "Resources"
  name = "Combo API Docs"
  url = "combodoc/"
  weight = 1
  
  [[main]]
  parent = "Resources"
  name = "Creds API Docs"
  url = "credsdoc/"
  weight = 2
  
  [[main]]
  parent = "Resources"
  name = "Darkweb API Docs"
  url = "darkwebdoc/"
  weight = 3
  
  [[main]]
  parent = "Resources"
  name = "Monitor API Docs"
  url = "monitordoc/"
  weight = 4
  
  [[main]]
  parent = "Resources"
  name = "Radar API Docs"
  url = "radardoc/"
  weight = 5
  
  [[main]]
  parent = "Resources"
  name = "Sessions API Docs"
  url = "sessionsdoc/"
  weight = 6
  
  [[main]]
  parent = "Resources"
  name = "Stealer API Docs"
  url = "stealerdoc/"
  weight = 7
  
  [[main]]
  parent = "Resources"
  name = "Darkweb API Docs"
  url = "darkwebdoc/"
  weight = 3
  
  [[main]]
  parent = "Resources"
  name = "Ransomware Gangs"
  url = "ransomware-gangs/"
  weight = 8

  [[main]]
  parent = "Resources"
  name = "Dark Web Monitoring"
  url = "dark-web-monitoring/"
  weight = 9
  
  [[main]]
  parent = "Resources"
  name = "Podcast"
  url = "podcast/"
  weight = 10

[[main]]
name = "About"
url = "about/"
weight = 7

[[main]]
name = "Latest Breaches"
url = "breaches/"
weight = 24

[[main]]
  name = "Check your exposure"
  url = "check-your-exposure/"
  weight = 25

# footer menu
[[footer]]
name = "About"
url = "about/"
weight = 1

[[footer]]
name = "Terms & Conditions"
url = "terms-and-conditions/"
weight = 3

