#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x"
logo_width = "240x"
# logo text will only show when logo is missing.
logo_text = "Breachsense"
# image gallery shortcode
image_gallery = true

# footer information
footer_info = "Real-time Data Breach Monitoring for the Enterprise"

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]
breachSections= ["breaches"]

# Change month format for /breaches page sidebar
[sidebar_breaches]
month_short_format = false # set it to true if you don't want full format of the month.

# contact information
[contact_info]
address = "23811 Chagrin Blvd. Ste 200 Beachwood, Ohio 44122"
phone = [""]
email = ["info@breachsense.com", "support@breachsense.com"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Book Demo"
link = "book-demo/"

# book_a_demo button
[book_a_demo]
label = "Book a demo"
link = "/book-demo#book-demo"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["data breach monitoring", "ransomware prevention", "Breachsense"]
#description = "Monitor for data breaches within your organization with Breachsense. Know when there’s a data breach in your organization and react in a timely manner."
author = "Breachsense"

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = false
title = "Helping teams in the world with focus"
content = "ipsum dolor sit amet, consectetur adipiscing elit. Morbi egestas <br> Werat viverra id et aliquet. vulputate egestas sollicitudin."
button = "Download The Theme"
button_link = "/"

############################# social site ########################
[[social]]
title = "AndromedaTweet"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "https://twitter.com/breachsense"

[[social]]
title = "AndromedaIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "https://www.linkedin.com/company/breachsense/"
